### ISSUE TITLE
Research Datasets for Philly Neighborhoods + Points of Interest

### ISSUE THREAD

**Issue by calemonte** [jpirrone104/Project2#2]
This dataset should include Philadelphia points of interest organized by region and (ideally) neighborhood.

**Comment by dalynat** [comment]
https://www.opendataphilly.org/dataset/city-landmarks

**Comment by dalynat** [comment]
https://www.opendataphilly.org/dataset/parks-and-recreation-assets

**Comment by dalynat** [comment]
Google Maps Places api 
https://developers.google.com/places/web-service/intro
Can search for places by area or by type of place (museum, night-club, bank, etc.)
Data returned includes: Formatted Address, Location, Name, Photo, Type, URL, User Ratings Total
